AllCops:
  TargetRubyVersion: "2.3"
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/**/*"

Style/IfUnlessModifier:
  Enabled: false
Style/DocumentationMethod:
  Enabled: true
Layout:
  Enabled: false
Metrics:
  Enabled: false
