AllCops:
  TargetRubyVersion: "2.3"
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "bin/**/*"

Style/Documentation:
  Enabled: false
Layout:
  Enabled: false
Metrics:
  Enabled: false
