version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Single Subscriber E2E Test
          command: cd spec/e2e/single-subscriber && ./test
