version: "3.7"

x-jstreams: &jstreams
  working_dir: /opt/jstreams/spec/e2e/single-subscriber
  build:
    context: ../../..
  environment:
    REDIS_URL: redis://redis
  volumes:
    - ../../..:/opt/jstreams
  depends_on:
    - redis

services:
  redis:
    image: redis:5

  publisher:
    <<: *jstreams
    command: ["ruby", "test_publisher.rb"]

  test:
    <<: *jstreams
    command: ["ruby", "test_subscriber.rb"]
